<a href="https://colab.research.google.com/github/omaralonsoinfo/MineriaDeDatos/blob/main/Mineria_de_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mineria de Datos

## Primer Parcial

### Introducción

#### Conceptos

#### Ciencia de Datos

 La ciencia de datos es un campo que combina matemáticas, estadística, programación y herramientas tecnológicas para analizar grandes cantidades de información y descubrir patrones

#### Mineria de Datos

 La minería de datos es el proceso de buscar patrones y conocimientos escondidos dentro de grandes cantidades de información, como si estuvieras buscando pepitas de oro en una mina.

#### Tarea 1 - Help and Documentation in IPython

In [ ]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
len?

In [ ]:
L = [1, 2, 3]
L.insert?

In [ ]:
L?

In [ ]:
def square(a):
  ....:     """Return the square of a."""
  ....:     return a ** 2
  ....:

In [ ]:
square?

In [ ]:
square??

In [ ]:
len??

In [ ]:
L.append #L. para ver la lista de lo que se puede hacer con el objeto
# + tab para seleccionarlo

<function list.append(object, /)>

In [ ]:
L.copy

<function list.copy()>

In [ ]:
L.count

<function list.count(value, /)>

In [ ]:
L.__add__

<method-wrapper '__add__' of list object at 0x7a57ee955180>

In [ ]:
from itertools import combinations

In [ ]:
import h2

In [ ]:
*Warning?

In [ ]:
str.*find*?

#### Python Magic Commands

In [3]:
#comando magico timeit pára evaluar el desempeño, en terminos de tiempo
#comparar si un algoritmo es mas rapido que otro
%timeit L = [n ** 2 for n in range(1000)]

88.1 µs ± 26.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [6]:
#comando magico sirve para evaluar el desempeño, solo que este abarca varias lineas de codigo en lugar de una linea
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

96.8 µs ± 28 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [7]:
%timeit?

In [8]:
%%timeit?

#### Python and Shield Comands

In [9]:
#Nos dice el directorio en el que estamos
!ls

sample_data


In [11]:
%cd sample_data/

/content/sample_data


In [12]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [14]:
%cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


In [15]:
#numpy fue creda en c ya que es mas rapido procesar datos en python
import numpy as np

In [16]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [17]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [18]:
np.array([1, 2, 3, 4], dtype='float32')


array([1., 2., 3., 4.], dtype=float32)

In [19]:
np.array([1, 2, 3, 4], dtype='int')


array([1, 2, 3, 4])

In [20]:
#podemos ahcer listas de contencion para hacer listas bidimensionales, con ciclos anidados
#punto inicial i, punto final i+3 sin contemplarlo
np.array([range(i, i + 3) for i in [2, 4, 6]])


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])