<a href="https://colab.research.google.com/github/omaralonsoinfo/MineriaDeDatos/blob/main/Mineria_de_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mineria de Datos

## Primer Parcial

### Introducción

#### Conceptos

#### Ciencia de Datos

 La ciencia de datos es un campo que combina matemáticas, estadística, programación y herramientas tecnológicas para analizar grandes cantidades de información y descubrir patrones

#### Mineria de Datos

 La minería de datos es el proceso de buscar patrones y conocimientos escondidos dentro de grandes cantidades de información, como si estuvieras buscando pepitas de oro en una mina.

#### Tarea 1 - Help and Documentation in IPython

In [ ]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
len?

In [ ]:
L = [1, 2, 3]
L.insert?

In [ ]:
L?

In [ ]:
def square(a):
  ....:     """Return the square of a."""
  ....:     return a ** 2
  ....:

In [ ]:
square?

In [ ]:
square??

In [ ]:
len??

In [ ]:
L.append #L. para ver la lista de lo que se puede hacer con el objeto
# + tab para seleccionarlo

<function list.append(object, /)>

In [ ]:
L.copy

<function list.copy()>

In [ ]:
L.count

<function list.count(value, /)>

In [ ]:
L.__add__

<method-wrapper '__add__' of list object at 0x7a57ee955180>

In [ ]:
from itertools import combinations

In [ ]:
import h2

In [ ]:
*Warning?

In [ ]:
str.*find*?

#### Python Magic Commands

In [ ]:
#comando magico timeit pára evaluar el desempeño, en terminos de tiempo
#comparar si un algoritmo es mas rapido que otro
%timeit L = [n ** 2 for n in range(1000)]

88.1 µs ± 26.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
#comando magico sirve para evaluar el desempeño, solo que este abarca varias lineas de codigo en lugar de una linea
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

96.8 µs ± 28 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
%timeit?

In [ ]:
%%timeit?

#### Python and Shield Comands

In [ ]:
#Nos dice el directorio en el que estamos
!ls

sample_data


In [ ]:
%cd sample_data/

/content/sample_data


In [ ]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [ ]:
%cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


In [ ]:
#numpy fue creda en c ya que es mas rapido procesar datos en python
import numpy as np

In [ ]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
np.array([1, 2, 3, 4], dtype='float32')


array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([1, 2, 3, 4], dtype='int')


array([1, 2, 3, 4])

In [ ]:
#podemos ahcer listas de contencion para hacer listas bidimensionales, con ciclos anidados
#punto inicial i, punto final i+3 sin contemplarlo
np.array([range(i, i + 3) for i in [2, 4, 6]])


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

#### The Basics of Numpy Arrays

In [1]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [4]:
print("x3 ndim: ", x3.ndim) # La propiedad ndim nos dice el numero de dimensiones
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size) # 3*4*5 = 60

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [5]:
print(x2.dtype) # dtype nos dice el tipo de datos

int64


In [6]:
#Itemsize nos regresa el tamaño en size
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes") #nbytes es el tamaño del elemento por el numero

itemsize: 8 bytes
nbytes: 480 bytes


#### Array Indexing: Accessing Single Elements

In [9]:
x1 #digitos entre 0 y 10 ya que indicamos que queriamos numeros enteros entre 0 y 10 con tamaño de arreglo = 6

array([5, 0, 3, 3, 7, 9])

In [8]:
x1[0] #colocamos el indice del elemento a extraer, en este caso el primer elemento tienen el indice 0

np.int64(5)

In [10]:
x1[4]

np.int64(7)

In [11]:
#para indexar de atras hacia adelante, utilizamos negativos
x1[-1] # nos regresa el ultimo elemento del ndarray

np.int64(9)

In [12]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [13]:
x2[0,0] #para bidi pasamos las cordenadas de X y Y

np.int64(3)

In [14]:
x2[0,2]

np.int64(2)

In [15]:
x2[2, -1]

np.int64(7)

In [18]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

### Estadistica Básica

#### Media (Mean)


In [19]:
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


#### Promedio (Average) y Promedio Ponderado


In [20]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

#### Mediana


In [21]:
mediana = np.median(data)

#### Varianza y Desviación Estándar


In [22]:
varianza = np.var(data)
desviacion = np.std(data) #desviacion raiz cuadrada de la varianza

#### 🔄 Generación de Datos Aleatorios


In [24]:
muestra = np.random.normal(0, 1, 1000)
print(np.mean(muestra), np.std(muestra)) #media tiende a cero , desviacion de 1 , genera mil datos

0.0024029618578246446 1.00901955868826


#### Correlacion

In [26]:
corr = np.corrcoef([1,2,3], [1,5,7])

#### 📊 Funciones Estadísticas Adicionales (NumPy)


In [28]:
#Cuantiles
(np.quantile)
#Percentiles
(np.percentile)
#Histogramas
(np.histogram)
#Covarianza
(np.cov)
#Manejo de NaN
(np.nanmean)

<function nanmean at 0x7a7cf3bc0ab0>